// @generated by lenso-contract-codegen; do not edit.
use std::{fmt, rc::Rc};
use futures::future::LocalBoxFuture;
use lenso_kernel::{InvocationContext, NativeRequestEndpoint, NativeRequestFuture, NativeRequestHandle, PluginDependencies, RequestCapability, RuntimeFailure};

use lenso_plugin_authoring::{BoundCapabilityClient, CapabilityClient, CapabilityClientMany};
pub const CAPABILITY_ID: &str = "lenso.notification.delivery@1";
pub const DESCRIPTOR_VERSION: &str = "1.0.0";
pub const PORTABLE: bool = true;
pub const CROSS_LANE_TRANSFER: bool = true;
pub const DELIVERY_CAPABILITY_ID: &str = CAPABILITY_ID;
pub const DELIVERY_DESCRIPTOR_VERSION: &str = DESCRIPTOR_VERSION;

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_provided_delivery { () => { "{\"capability_id\":\"lenso.notification.delivery@1\",\"descriptor_version\":\"1.0.0\",\"operations\":[\"dispatch_due\",\"observe_receipt\"],\"operation_kinds\":{},\"default_admission\":{\"queue_capacity\":0,\"max_concurrency\":1},\"operation_admissions\":{},\"event_admission\":null,\"cross_lane_transfer\":true}" }; }

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_required_delivery_client { () => { "{\"capability_id\":\"lenso.notification.delivery@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"one\"}" }; }

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_required_many_delivery_client { () => { "{\"capability_id\":\"lenso.notification.delivery@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"many\"}" }; }

pub const DISPATCH_DUE_OPERATION: &str = "dispatch_due";
pub const OBSERVE_RECEIPT_OPERATION: &str = "observe_receipt";

pub use lenso_contract_runtime::{Timestamp, UnknownDomainError};
use lenso_contract_runtime::{decode_portable_json, encode_portable_json};

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct DispatchDueRequest {

}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct DispatchDueResponse {
    #[serde(rename = "attempt_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub attempt_id: String,
    #[serde(rename = "delivery_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub delivery_id: String,
    #[serde(rename = "next_attempt_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub next_attempt_at: Option<Timestamp>,
    #[serde(rename = "observed_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub observed_at: Timestamp,
    #[serde(rename = "run_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub run_id: String,
    #[serde(rename = "status")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub status: DispatchDueResponseStatus,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub enum DispatchDueResponseStatus {
    #[serde(rename = "accepted")]
    Accepted,
    #[serde(rename = "retry_scheduled")]
    RetryScheduled,
    #[serde(rename = "failed")]
    Failed,
    #[serde(rename = "delivery_unknown")]
    DeliveryUnknown,
}

#[derive(Clone, Debug, PartialEq)]
pub enum DispatchDueError {
    DispatchRejected,
    NoDeliveryDue,
    Unauthorized,
    Unknown(UnknownDomainError),
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ObserveReceiptRequest {
    #[serde(rename = "attempt_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub attempt_id: String,
    #[serde(rename = "delivery_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub delivery_id: String,
    #[serde(rename = "digest")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub digest: String,
    #[serde(rename = "kind")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub kind: ObserveReceiptRequestKind,
    #[serde(rename = "observation_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub observation_id: String,
    #[serde(rename = "observed_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub observed_at: Timestamp,
    #[serde(rename = "remote_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub remote_id: String,
    #[serde(rename = "run_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub run_id: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub enum ObserveReceiptRequestKind {
    #[serde(rename = "delivered")]
    Delivered,
    #[serde(rename = "bounced")]
    Bounced,
    #[serde(rename = "rejected")]
    Rejected,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ObserveReceiptResponse {
    #[serde(rename = "recorded")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub recorded: bool,
}

#[derive(Clone, Debug, PartialEq)]
pub enum ObserveReceiptError {
    DeliveryNotFound,
    InvalidReceipt,
    ReceiptConflict,
    Unauthorized,
    Unknown(UnknownDomainError),
}

#[derive(Debug)]
pub struct DeliveryDispatchDue;
impl RequestCapability for DeliveryDispatchDue {
    type Request = DispatchDueRequest;
    type Response = DispatchDueResponse;
    type DomainError = DispatchDueError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != DISPATCH_DUE_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<DeliveryRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).dispatch_due(context, request)
    }
}

#[derive(Debug)]
pub struct DeliveryObserveReceipt;
impl RequestCapability for DeliveryObserveReceipt {
    type Request = ObserveReceiptRequest;
    type Response = ObserveReceiptResponse;
    type DomainError = ObserveReceiptError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != OBSERVE_RECEIPT_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<DeliveryRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).observe_receipt(context, request)
    }
}

impl serde::Serialize for DispatchDueError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::DispatchRejected => serializer.serialize_str("dispatch_rejected"),
            Self::NoDeliveryDue => serializer.serialize_str("no_delivery_due"),
            Self::Unauthorized => serializer.serialize_str("unauthorized"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for DispatchDueError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "dispatch_rejected" => Ok(Self::DispatchRejected),
                "no_delivery_due" => Ok(Self::NoDeliveryDue),
                "unauthorized" => Ok(Self::Unauthorized),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

impl serde::Serialize for ObserveReceiptError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::DeliveryNotFound => serializer.serialize_str("delivery_not_found"),
            Self::InvalidReceipt => serializer.serialize_str("invalid_receipt"),
            Self::ReceiptConflict => serializer.serialize_str("receipt_conflict"),
            Self::Unauthorized => serializer.serialize_str("unauthorized"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for ObserveReceiptError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "delivery_not_found" => Ok(Self::DeliveryNotFound),
                "invalid_receipt" => Ok(Self::InvalidReceipt),
                "receipt_conflict" => Ok(Self::ReceiptConflict),
                "unauthorized" => Ok(Self::Unauthorized),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

pub fn encode_dispatch_due_request(value: &DispatchDueRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_dispatch_due_request(wire: &str) -> Result<DispatchDueRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_dispatch_due_response(value: &DispatchDueResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_dispatch_due_response(wire: &str) -> Result<DispatchDueResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_dispatch_due_error(value: &DispatchDueError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_dispatch_due_error(wire: &str) -> Result<DispatchDueError, serde_json::Error> { decode_portable_json(wire) }

pub fn encode_observe_receipt_request(value: &ObserveReceiptRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_observe_receipt_request(wire: &str) -> Result<ObserveReceiptRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_observe_receipt_response(value: &ObserveReceiptResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_observe_receipt_response(wire: &str) -> Result<ObserveReceiptResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_observe_receipt_error(value: &ObserveReceiptError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_observe_receipt_error(wire: &str) -> Result<ObserveReceiptError, serde_json::Error> { decode_portable_json(wire) }

#[doc(hidden)]
pub trait __LensoIntoDeliveryDispatchDueResult {
    fn __lenso_into_result(self) -> Result<Result<DispatchDueResponse, DispatchDueError>, RuntimeFailure>;
}
impl __LensoIntoDeliveryDispatchDueResult for Result<DispatchDueResponse, DispatchDueError> {
    fn __lenso_into_result(self) -> Result<Result<DispatchDueResponse, DispatchDueError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoDeliveryDispatchDueResult for Result<Result<DispatchDueResponse, DispatchDueError>, RuntimeFailure> {
    fn __lenso_into_result(self) -> Result<Result<DispatchDueResponse, DispatchDueError>, RuntimeFailure> { self }
}
impl __LensoIntoDeliveryDispatchDueResult for Result<DispatchDueResponse, lenso_plugin_authoring::PluginError<DispatchDueError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<DispatchDueResponse, DispatchDueError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Ok(Err(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoDeliveryDispatchDueResult for Result<DispatchDueResponse, DeliveryDispatchDueInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<DispatchDueResponse, DispatchDueError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(DeliveryDispatchDueInvocationError::Domain(error)) => Ok(Err(error)),
            Err(DeliveryDispatchDueInvocationError::Runtime(error)) => Err(error),
        }
    }
}

#[doc(hidden)]
pub trait __LensoIntoDeliveryObserveReceiptResult {
    fn __lenso_into_result(self) -> Result<Result<ObserveReceiptResponse, ObserveReceiptError>, RuntimeFailure>;
}
impl __LensoIntoDeliveryObserveReceiptResult for Result<ObserveReceiptResponse, ObserveReceiptError> {
    fn __lenso_into_result(self) -> Result<Result<ObserveReceiptResponse, ObserveReceiptError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoDeliveryObserveReceiptResult for Result<Result<ObserveReceiptResponse, ObserveReceiptError>, RuntimeFailure> {
    fn __lenso_into_result(self) -> Result<Result<ObserveReceiptResponse, ObserveReceiptError>, RuntimeFailure> { self }
}
impl __LensoIntoDeliveryObserveReceiptResult for Result<ObserveReceiptResponse, lenso_plugin_authoring::PluginError<ObserveReceiptError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<ObserveReceiptResponse, ObserveReceiptError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Ok(Err(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoDeliveryObserveReceiptResult for Result<ObserveReceiptResponse, DeliveryObserveReceiptInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<ObserveReceiptResponse, ObserveReceiptError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(DeliveryObserveReceiptInvocationError::Domain(error)) => Ok(Err(error)),
            Err(DeliveryObserveReceiptInvocationError::Runtime(error)) => Err(error),
        }
    }
}

pub trait DeliveryProvider: fmt::Debug + 'static {
    fn dispatch_due(&self, context: InvocationContext, request: DispatchDueRequest) -> NativeRequestFuture<DeliveryDispatchDue>;
    fn observe_receipt(&self, context: InvocationContext, request: ObserveReceiptRequest) -> NativeRequestFuture<DeliveryObserveReceipt>;
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_lower_delivery {
    ($plugin:ty, $support:path) => {
        use $support as __LensoNativeSupportDelivery;
        impl $crate::DeliveryProvider for $plugin {
        fn dispatch_due(&self, context: __LensoNativeSupportDelivery::InvocationContext, request: $crate::DispatchDueRequest) -> __LensoNativeSupportDelivery::NativeRequestFuture<$crate::DeliveryDispatchDue> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::dispatch_due(&plugin, context, request).await;
                $crate::__LensoIntoDeliveryDispatchDueResult::__lenso_into_result(result)
            })
        }
        fn observe_receipt(&self, context: __LensoNativeSupportDelivery::InvocationContext, request: $crate::ObserveReceiptRequest) -> __LensoNativeSupportDelivery::NativeRequestFuture<$crate::DeliveryObserveReceipt> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::observe_receipt(&plugin, context, request).await;
                $crate::__LensoIntoDeliveryObserveReceiptResult::__lenso_into_result(result)
            })
        }
        }
    };
}

#[derive(Debug)]
struct DeliveryRequestEndpoint { provider: Rc<dyn DeliveryProvider> }

#[derive(Debug)]
pub struct DeliveryEndpoint<P: DeliveryProvider> { provider: Rc<P>, request_endpoint: DeliveryRequestEndpoint }
impl<P: DeliveryProvider> DeliveryEndpoint<P> {
    pub fn new(provider: P) -> Self {
        let provider = Rc::new(provider);
        let request_provider: Rc<dyn DeliveryProvider> = provider.clone();
        Self { provider, request_endpoint: DeliveryRequestEndpoint { provider: request_provider } }
    }
}

impl<P: DeliveryProvider> NativeRequestEndpoint for DeliveryEndpoint<P> {
    fn capability_id(&self) -> &'static str { CAPABILITY_ID }
    fn descriptor_version(&self) -> &'static str { DESCRIPTOR_VERSION }
    fn operations(&self) -> &'static [&'static str] { &[
        DISPATCH_DUE_OPERATION,
        OBSERVE_RECEIPT_OPERATION,
    ] }
    fn typed_endpoint(&self) -> Option<&dyn std::any::Any> { Some(&self.request_endpoint) }
    fn invoke(&self, operation: &str, request: Box<dyn std::any::Any>, context: InvocationContext) -> LocalBoxFuture<'static, Result<Result<Box<dyn std::any::Any>, Box<dyn std::any::Any>>, RuntimeFailure>> {
        match operation {
            DISPATCH_DUE_OPERATION => {
                let Ok(request) = request.downcast::<DispatchDueRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).dispatch_due(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            },
            OBSERVE_RECEIPT_OPERATION => {
                let Ok(request) = request.downcast::<ObserveReceiptRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).observe_receipt(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            }
            _ => Box::pin(futures::future::ready(Err(RuntimeFailure::UnknownOperation { capability: CAPABILITY_ID, operation: operation.to_owned() }))),
        }
    }
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_endpoints_delivery {
    ($provider:expr, $support:path) => {{
        use $support as __LensoNativeSupport;
        let endpoint = ::std::rc::Rc::new($crate::DeliveryEndpoint::new($provider));
        (
            vec![endpoint.clone() as ::std::rc::Rc<dyn __LensoNativeSupport::NativeRequestEndpoint>],
            vec![],
            vec![],
        )
    }};
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_provide_delivery {
    ($provider:expr, $lifecycle:expr, $support:path) => {{
        use $support as __LensoNativeSupport;
        let (request_endpoints, stream_endpoints, event_endpoints) =
            $crate::__lenso_native_endpoints_delivery!($provider, $support);
        __LensoNativeSupport::NativePluginInstance::with_all_endpoints(
            request_endpoints,
            stream_endpoints,
            event_endpoints,
            $lifecycle,
        )
    }};
}

#[derive(Debug)]
pub struct DeliveryClient {
    dispatch_due: NativeRequestHandle<DeliveryDispatchDue>,
    observe_receipt: NativeRequestHandle<DeliveryObserveReceipt>,
}
impl DeliveryClient {
    pub fn from_dependencies(dependencies: &PluginDependencies) -> Result<Self, RuntimeFailure> {
        <Self as CapabilityClient>::from_dependencies(dependencies)
    }

    pub async fn dispatch_due(&self, request: DispatchDueRequest) -> Result<DispatchDueResponse, DeliveryDispatchDueInvocationError> {
        self.dispatch_due.invoke(DISPATCH_DUE_OPERATION, request).await
            .map_err(DeliveryDispatchDueInvocationError::Runtime)?
            .map_err(DeliveryDispatchDueInvocationError::Domain)
    }

    pub async fn dispatch_due_with_context(&self, context: InvocationContext, request: DispatchDueRequest) -> Result<DispatchDueResponse, DeliveryDispatchDueInvocationError> {
        self.dispatch_due.invoke_with_context(DISPATCH_DUE_OPERATION, context, request).await
            .map_err(DeliveryDispatchDueInvocationError::Runtime)?
            .map_err(DeliveryDispatchDueInvocationError::Domain)
    }

    pub async fn observe_receipt(&self, request: ObserveReceiptRequest) -> Result<ObserveReceiptResponse, DeliveryObserveReceiptInvocationError> {
        self.observe_receipt.invoke(OBSERVE_RECEIPT_OPERATION, request).await
            .map_err(DeliveryObserveReceiptInvocationError::Runtime)?
            .map_err(DeliveryObserveReceiptInvocationError::Domain)
    }

    pub async fn observe_receipt_with_context(&self, context: InvocationContext, request: ObserveReceiptRequest) -> Result<ObserveReceiptResponse, DeliveryObserveReceiptInvocationError> {
        self.observe_receipt.invoke_with_context(OBSERVE_RECEIPT_OPERATION, context, request).await
            .map_err(DeliveryObserveReceiptInvocationError::Runtime)?
            .map_err(DeliveryObserveReceiptInvocationError::Domain)
    }
}

impl CapabilityClient for DeliveryClient {
    type Dependencies = PluginDependencies;
    type Error = RuntimeFailure;

    const CAPABILITY_ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn from_dependencies(dependencies: &PluginDependencies) -> Result<Self, RuntimeFailure> {
        Ok(Self {
            dispatch_due: dependencies.one::<DeliveryDispatchDue>()?,
            observe_receipt: dependencies.one::<DeliveryObserveReceipt>()?,
        })
    }

    fn already_connected() -> RuntimeFailure {
        RuntimeFailure::PluginFailure {
            detail: format!("Capability Port {CAPABILITY_ID} was connected more than once"),
        }
    }
}

impl CapabilityClientMany for DeliveryClient {
    fn many_from_dependencies(
        dependencies: &PluginDependencies,
    ) -> Result<Vec<BoundCapabilityClient<Self>>, RuntimeFailure> {
        dependencies
            .bindings()
            .iter()
            .filter(|binding| binding.capability_id() == CAPABILITY_ID)
            .map(|binding| {
                Ok(BoundCapabilityClient::new(
                    binding.provider_instance(),
                    Self {
                    dispatch_due: binding.handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<DeliveryDispatchDue>()?,
                    observe_receipt: binding.handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<DeliveryObserveReceipt>()?,
                    },
                ))
            })
            .collect()
    }
}

#[derive(Clone, Debug, PartialEq)]
pub enum DeliveryDispatchDueInvocationError {
    Domain(DispatchDueError),
    Runtime(RuntimeFailure),
}
#[derive(Clone, Debug, PartialEq)]
pub enum DeliveryObserveReceiptInvocationError {
    Domain(ObserveReceiptError),
    Runtime(RuntimeFailure),
}
