// @generated by lenso-contract-codegen; do not edit.
use std::{fmt, rc::Rc};
use futures::future::LocalBoxFuture;
use lenso_kernel::{InvocationContext, NativeRequestEndpoint, NativeRequestFuture, NativeRequestHandle, PluginDependencies, RequestCapability, RuntimeFailure};

use lenso_plugin_authoring::{BoundCapabilityClient, CapabilityClient, CapabilityClientMany};
pub const CAPABILITY_ID: &str = "lenso.notification.admin@1";
pub const DESCRIPTOR_VERSION: &str = "1.0.0";
pub const PORTABLE: bool = true;
pub const CROSS_LANE_TRANSFER: bool = true;
pub const ADMIN_CAPABILITY_ID: &str = CAPABILITY_ID;
pub const ADMIN_DESCRIPTOR_VERSION: &str = DESCRIPTOR_VERSION;

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_provided_admin { () => { "{\"capability_id\":\"lenso.notification.admin@1\",\"descriptor_version\":\"1.0.0\",\"operations\":[\"get_delivery\",\"list_deliveries\",\"retry_delivery\"],\"operation_kinds\":{},\"default_admission\":{\"queue_capacity\":0,\"max_concurrency\":1},\"operation_admissions\":{},\"event_admission\":null,\"cross_lane_transfer\":true}" }; }

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_required_admin_client { () => { "{\"capability_id\":\"lenso.notification.admin@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"one\"}" }; }

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_required_many_admin_client { () => { "{\"capability_id\":\"lenso.notification.admin@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"many\"}" }; }

pub const GET_DELIVERY_OPERATION: &str = "get_delivery";
pub const LIST_DELIVERIES_OPERATION: &str = "list_deliveries";
pub const RETRY_DELIVERY_OPERATION: &str = "retry_delivery";

pub use lenso_contract_runtime::{Timestamp, UnknownDomainError};
use lenso_contract_runtime::{decode_portable_json, encode_portable_json};

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct GetDeliveryRequest {
    #[serde(rename = "delivery_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub delivery_id: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct GetDeliveryResponse {
    #[serde(rename = "attempts")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub attempts: Vec<Attempt>,
    #[serde(rename = "delivery")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub delivery: Delivery,
    #[serde(rename = "open_in_story_correlation_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub open_in_story_correlation_id: String,
    #[serde(rename = "receipts")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub receipts: Vec<Receipt>,
    #[serde(rename = "retry_requests")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub retry_requests: Vec<RetryRecord>,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct Attempt {
    #[serde(rename = "completed_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub completed_at: Option<Timestamp>,
    #[serde(rename = "failure_classification")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub failure_classification: Option<String>,
    #[serde(rename = "failure_code")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub failure_code: Option<String>,
    #[serde(rename = "id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub id: String,
    #[serde(rename = "provider")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub provider: Option<String>,
    #[serde(rename = "remote_receipt_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub remote_receipt_id: Option<String>,
    #[serde(rename = "run_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub run_id: String,
    #[serde(rename = "sequence")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub sequence: i64,
    #[serde(rename = "started_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub started_at: Timestamp,
    #[serde(rename = "status")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub status: AttemptStatus,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub enum AttemptStatus {
    #[serde(rename = "dispatching")]
    Dispatching,
    #[serde(rename = "accepted")]
    Accepted,
    #[serde(rename = "temporary_failure")]
    TemporaryFailure,
    #[serde(rename = "permanent_failure")]
    PermanentFailure,
    #[serde(rename = "delivery_unknown")]
    DeliveryUnknown,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct Delivery {
    #[serde(rename = "attempt_count")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub attempt_count: i64,
    #[serde(rename = "content_digest")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub content_digest: String,
    #[serde(rename = "correlation_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub correlation_id: String,
    #[serde(rename = "created_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub created_at: Timestamp,
    #[serde(rename = "final_reason")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub final_reason: Option<String>,
    #[serde(rename = "id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub id: String,
    #[serde(rename = "locale")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub locale: String,
    #[serde(rename = "max_attempts")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub max_attempts: i64,
    #[serde(rename = "next_attempt_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub next_attempt_at: Option<Timestamp>,
    #[serde(rename = "recipient_mask")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub recipient_mask: String,
    #[serde(rename = "redacted_preview")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub redacted_preview: String,
    #[serde(rename = "retry_now_eligible")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub retry_now_eligible: bool,
    #[serde(rename = "revision")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub revision: i64,
    #[serde(rename = "status")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub status: DeliveryStatus,
    #[serde(rename = "template_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub template_id: String,
    #[serde(rename = "template_version")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub template_version: String,
    #[serde(rename = "updated_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub updated_at: Timestamp,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub enum DeliveryStatus {
    #[serde(rename = "queued")]
    Queued,
    #[serde(rename = "attempting")]
    Attempting,
    #[serde(rename = "accepted")]
    Accepted,
    #[serde(rename = "retry_scheduled")]
    RetryScheduled,
    #[serde(rename = "delivered")]
    Delivered,
    #[serde(rename = "failed")]
    Failed,
    #[serde(rename = "delivery_unknown")]
    DeliveryUnknown,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct Receipt {
    #[serde(rename = "attempt_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub attempt_id: String,
    #[serde(rename = "digest")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub digest: String,
    #[serde(rename = "id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub id: String,
    #[serde(rename = "kind")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub kind: ReceiptKind,
    #[serde(rename = "observed_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub observed_at: Timestamp,
    #[serde(rename = "remote_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub remote_id: String,
    #[serde(rename = "source")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub source: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub enum ReceiptKind {
    #[serde(rename = "accepted")]
    Accepted,
    #[serde(rename = "delivered")]
    Delivered,
    #[serde(rename = "bounced")]
    Bounced,
    #[serde(rename = "rejected")]
    Rejected,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct RetryRecord {
    #[serde(rename = "created_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub created_at: Timestamp,
    #[serde(rename = "decision")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub decision: RetryRecordDecision,
    #[serde(rename = "id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub id: String,
    #[serde(rename = "kind")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub kind: RetryRecordKind,
    #[serde(rename = "reason")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub reason: Option<String>,
    #[serde(rename = "requested_by")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub requested_by: Option<String>,
    #[serde(rename = "scheduled_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub scheduled_at: Option<Timestamp>,
    #[serde(rename = "source_revision")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub source_revision: i64,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub enum RetryRecordDecision {
    #[serde(rename = "scheduled")]
    Scheduled,
    #[serde(rename = "rejected")]
    Rejected,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub enum RetryRecordKind {
    #[serde(rename = "automatic")]
    Automatic,
    #[serde(rename = "manual")]
    Manual,
}

#[derive(Clone, Debug, PartialEq)]
pub enum GetDeliveryError {
    DeliveryNotFound,
    EvidenceOverflow,
    InvalidRequest,
    Unauthorized,
    Unknown(UnknownDomainError),
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ListDeliveriesRequest {
    #[serde(rename = "cursor")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cursor: Option<String>,
    #[serde(rename = "limit")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub limit: Option<i64>,
    #[serde(rename = "status")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub status: Option<DeliveryStatus>,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ListDeliveriesResponse {
    #[serde(rename = "next_cursor")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub next_cursor: Option<String>,
    #[serde(rename = "records")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub records: Vec<Delivery>,
}

#[derive(Clone, Debug, PartialEq)]
pub enum ListDeliveriesError {
    InvalidFilter,
    Unauthorized,
    Unknown(UnknownDomainError),
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct RetryDeliveryRequest {
    #[serde(rename = "delivery_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub delivery_id: String,
    #[serde(rename = "idempotency_key")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub idempotency_key: String,
    #[serde(rename = "revision")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub revision: i64,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct RetryDeliveryResponse {
    #[serde(rename = "delivery_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub delivery_id: String,
    #[serde(rename = "idempotent_replay")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub idempotent_replay: bool,
    #[serde(rename = "revision")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub revision: i64,
    #[serde(rename = "scheduled_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub scheduled_at: Timestamp,
    #[serde(rename = "status")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub status: RetryDeliveryResponseStatus,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub enum RetryDeliveryResponseStatus {
    #[serde(rename = "retry_scheduled")]
    RetryScheduled,
}

#[derive(Clone, Debug, PartialEq)]
pub enum RetryDeliveryError {
    DeliveryNotFound,
    IdempotencyConflict,
    InvalidRequest,
    RetryNotAllowed,
    StaleRevision,
    Unauthorized,
    Unknown(UnknownDomainError),
}

#[derive(Debug)]
pub struct AdminGetDelivery;
impl RequestCapability for AdminGetDelivery {
    type Request = GetDeliveryRequest;
    type Response = GetDeliveryResponse;
    type DomainError = GetDeliveryError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != GET_DELIVERY_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<AdminRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).get_delivery(context, request)
    }
}

#[derive(Debug)]
pub struct AdminListDeliveries;
impl RequestCapability for AdminListDeliveries {
    type Request = ListDeliveriesRequest;
    type Response = ListDeliveriesResponse;
    type DomainError = ListDeliveriesError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != LIST_DELIVERIES_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<AdminRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).list_deliveries(context, request)
    }
}

#[derive(Debug)]
pub struct AdminRetryDelivery;
impl RequestCapability for AdminRetryDelivery {
    type Request = RetryDeliveryRequest;
    type Response = RetryDeliveryResponse;
    type DomainError = RetryDeliveryError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != RETRY_DELIVERY_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<AdminRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).retry_delivery(context, request)
    }
}

impl serde::Serialize for GetDeliveryError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::DeliveryNotFound => serializer.serialize_str("delivery_not_found"),
            Self::EvidenceOverflow => serializer.serialize_str("evidence_overflow"),
            Self::InvalidRequest => serializer.serialize_str("invalid_request"),
            Self::Unauthorized => serializer.serialize_str("unauthorized"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for GetDeliveryError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "delivery_not_found" => Ok(Self::DeliveryNotFound),
                "evidence_overflow" => Ok(Self::EvidenceOverflow),
                "invalid_request" => Ok(Self::InvalidRequest),
                "unauthorized" => Ok(Self::Unauthorized),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

impl serde::Serialize for ListDeliveriesError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::InvalidFilter => serializer.serialize_str("invalid_filter"),
            Self::Unauthorized => serializer.serialize_str("unauthorized"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for ListDeliveriesError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "invalid_filter" => Ok(Self::InvalidFilter),
                "unauthorized" => Ok(Self::Unauthorized),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

impl serde::Serialize for RetryDeliveryError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::DeliveryNotFound => serializer.serialize_str("delivery_not_found"),
            Self::IdempotencyConflict => serializer.serialize_str("idempotency_conflict"),
            Self::InvalidRequest => serializer.serialize_str("invalid_request"),
            Self::RetryNotAllowed => serializer.serialize_str("retry_not_allowed"),
            Self::StaleRevision => serializer.serialize_str("stale_revision"),
            Self::Unauthorized => serializer.serialize_str("unauthorized"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for RetryDeliveryError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "delivery_not_found" => Ok(Self::DeliveryNotFound),
                "idempotency_conflict" => Ok(Self::IdempotencyConflict),
                "invalid_request" => Ok(Self::InvalidRequest),
                "retry_not_allowed" => Ok(Self::RetryNotAllowed),
                "stale_revision" => Ok(Self::StaleRevision),
                "unauthorized" => Ok(Self::Unauthorized),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

pub fn encode_get_delivery_request(value: &GetDeliveryRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_get_delivery_request(wire: &str) -> Result<GetDeliveryRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_get_delivery_response(value: &GetDeliveryResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_get_delivery_response(wire: &str) -> Result<GetDeliveryResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_get_delivery_error(value: &GetDeliveryError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_get_delivery_error(wire: &str) -> Result<GetDeliveryError, serde_json::Error> { decode_portable_json(wire) }

pub fn encode_list_deliveries_request(value: &ListDeliveriesRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_list_deliveries_request(wire: &str) -> Result<ListDeliveriesRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_list_deliveries_response(value: &ListDeliveriesResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_list_deliveries_response(wire: &str) -> Result<ListDeliveriesResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_list_deliveries_error(value: &ListDeliveriesError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_list_deliveries_error(wire: &str) -> Result<ListDeliveriesError, serde_json::Error> { decode_portable_json(wire) }

pub fn encode_retry_delivery_request(value: &RetryDeliveryRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_retry_delivery_request(wire: &str) -> Result<RetryDeliveryRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_retry_delivery_response(value: &RetryDeliveryResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_retry_delivery_response(wire: &str) -> Result<RetryDeliveryResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_retry_delivery_error(value: &RetryDeliveryError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_retry_delivery_error(wire: &str) -> Result<RetryDeliveryError, serde_json::Error> { decode_portable_json(wire) }

#[doc(hidden)]
pub trait __LensoIntoAdminGetDeliveryResult {
    fn __lenso_into_result(self) -> Result<Result<GetDeliveryResponse, GetDeliveryError>, RuntimeFailure>;
}
impl __LensoIntoAdminGetDeliveryResult for Result<GetDeliveryResponse, GetDeliveryError> {
    fn __lenso_into_result(self) -> Result<Result<GetDeliveryResponse, GetDeliveryError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoAdminGetDeliveryResult for Result<Result<GetDeliveryResponse, GetDeliveryError>, RuntimeFailure> {
    fn __lenso_into_result(self) -> Result<Result<GetDeliveryResponse, GetDeliveryError>, RuntimeFailure> { self }
}
impl __LensoIntoAdminGetDeliveryResult for Result<GetDeliveryResponse, lenso_plugin_authoring::PluginError<GetDeliveryError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<GetDeliveryResponse, GetDeliveryError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Ok(Err(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoAdminGetDeliveryResult for Result<GetDeliveryResponse, AdminGetDeliveryInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<GetDeliveryResponse, GetDeliveryError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(AdminGetDeliveryInvocationError::Domain(error)) => Ok(Err(error)),
            Err(AdminGetDeliveryInvocationError::Runtime(error)) => Err(error),
        }
    }
}

#[doc(hidden)]
pub trait __LensoIntoAdminListDeliveriesResult {
    fn __lenso_into_result(self) -> Result<Result<ListDeliveriesResponse, ListDeliveriesError>, RuntimeFailure>;
}
impl __LensoIntoAdminListDeliveriesResult for Result<ListDeliveriesResponse, ListDeliveriesError> {
    fn __lenso_into_result(self) -> Result<Result<ListDeliveriesResponse, ListDeliveriesError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoAdminListDeliveriesResult for Result<Result<ListDeliveriesResponse, ListDeliveriesError>, RuntimeFailure> {
    fn __lenso_into_result(self) -> Result<Result<ListDeliveriesResponse, ListDeliveriesError>, RuntimeFailure> { self }
}
impl __LensoIntoAdminListDeliveriesResult for Result<ListDeliveriesResponse, lenso_plugin_authoring::PluginError<ListDeliveriesError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<ListDeliveriesResponse, ListDeliveriesError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Ok(Err(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoAdminListDeliveriesResult for Result<ListDeliveriesResponse, AdminListDeliveriesInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<ListDeliveriesResponse, ListDeliveriesError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(AdminListDeliveriesInvocationError::Domain(error)) => Ok(Err(error)),
            Err(AdminListDeliveriesInvocationError::Runtime(error)) => Err(error),
        }
    }
}

#[doc(hidden)]
pub trait __LensoIntoAdminRetryDeliveryResult {
    fn __lenso_into_result(self) -> Result<Result<RetryDeliveryResponse, RetryDeliveryError>, RuntimeFailure>;
}
impl __LensoIntoAdminRetryDeliveryResult for Result<RetryDeliveryResponse, RetryDeliveryError> {
    fn __lenso_into_result(self) -> Result<Result<RetryDeliveryResponse, RetryDeliveryError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoAdminRetryDeliveryResult for Result<Result<RetryDeliveryResponse, RetryDeliveryError>, RuntimeFailure> {
    fn __lenso_into_result(self) -> Result<Result<RetryDeliveryResponse, RetryDeliveryError>, RuntimeFailure> { self }
}
impl __LensoIntoAdminRetryDeliveryResult for Result<RetryDeliveryResponse, lenso_plugin_authoring::PluginError<RetryDeliveryError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<RetryDeliveryResponse, RetryDeliveryError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Ok(Err(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoAdminRetryDeliveryResult for Result<RetryDeliveryResponse, AdminRetryDeliveryInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<RetryDeliveryResponse, RetryDeliveryError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(AdminRetryDeliveryInvocationError::Domain(error)) => Ok(Err(error)),
            Err(AdminRetryDeliveryInvocationError::Runtime(error)) => Err(error),
        }
    }
}

pub trait AdminProvider: fmt::Debug + 'static {
    fn get_delivery(&self, context: InvocationContext, request: GetDeliveryRequest) -> NativeRequestFuture<AdminGetDelivery>;
    fn list_deliveries(&self, context: InvocationContext, request: ListDeliveriesRequest) -> NativeRequestFuture<AdminListDeliveries>;
    fn retry_delivery(&self, context: InvocationContext, request: RetryDeliveryRequest) -> NativeRequestFuture<AdminRetryDelivery>;
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_lower_admin {
    ($plugin:ty, $support:path) => {
        use $support as __LensoNativeSupportAdmin;
        impl $crate::AdminProvider for $plugin {
        fn get_delivery(&self, context: __LensoNativeSupportAdmin::InvocationContext, request: $crate::GetDeliveryRequest) -> __LensoNativeSupportAdmin::NativeRequestFuture<$crate::AdminGetDelivery> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::get_delivery(&plugin, context, request).await;
                $crate::__LensoIntoAdminGetDeliveryResult::__lenso_into_result(result)
            })
        }
        fn list_deliveries(&self, context: __LensoNativeSupportAdmin::InvocationContext, request: $crate::ListDeliveriesRequest) -> __LensoNativeSupportAdmin::NativeRequestFuture<$crate::AdminListDeliveries> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::list_deliveries(&plugin, context, request).await;
                $crate::__LensoIntoAdminListDeliveriesResult::__lenso_into_result(result)
            })
        }
        fn retry_delivery(&self, context: __LensoNativeSupportAdmin::InvocationContext, request: $crate::RetryDeliveryRequest) -> __LensoNativeSupportAdmin::NativeRequestFuture<$crate::AdminRetryDelivery> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::retry_delivery(&plugin, context, request).await;
                $crate::__LensoIntoAdminRetryDeliveryResult::__lenso_into_result(result)
            })
        }
        }
    };
}

#[derive(Debug)]
struct AdminRequestEndpoint { provider: Rc<dyn AdminProvider> }

#[derive(Debug)]
pub struct AdminEndpoint<P: AdminProvider> { provider: Rc<P>, request_endpoint: AdminRequestEndpoint }
impl<P: AdminProvider> AdminEndpoint<P> {
    pub fn new(provider: P) -> Self {
        let provider = Rc::new(provider);
        let request_provider: Rc<dyn AdminProvider> = provider.clone();
        Self { provider, request_endpoint: AdminRequestEndpoint { provider: request_provider } }
    }
}

impl<P: AdminProvider> NativeRequestEndpoint for AdminEndpoint<P> {
    fn capability_id(&self) -> &'static str { CAPABILITY_ID }
    fn descriptor_version(&self) -> &'static str { DESCRIPTOR_VERSION }
    fn operations(&self) -> &'static [&'static str] { &[
        GET_DELIVERY_OPERATION,
        LIST_DELIVERIES_OPERATION,
        RETRY_DELIVERY_OPERATION,
    ] }
    fn typed_endpoint(&self) -> Option<&dyn std::any::Any> { Some(&self.request_endpoint) }
    fn invoke(&self, operation: &str, request: Box<dyn std::any::Any>, context: InvocationContext) -> LocalBoxFuture<'static, Result<Result<Box<dyn std::any::Any>, Box<dyn std::any::Any>>, RuntimeFailure>> {
        match operation {
            GET_DELIVERY_OPERATION => {
                let Ok(request) = request.downcast::<GetDeliveryRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).get_delivery(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            },
            LIST_DELIVERIES_OPERATION => {
                let Ok(request) = request.downcast::<ListDeliveriesRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).list_deliveries(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            },
            RETRY_DELIVERY_OPERATION => {
                let Ok(request) = request.downcast::<RetryDeliveryRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).retry_delivery(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            }
            _ => Box::pin(futures::future::ready(Err(RuntimeFailure::UnknownOperation { capability: CAPABILITY_ID, operation: operation.to_owned() }))),
        }
    }
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_endpoints_admin {
    ($provider:expr, $support:path) => {{
        use $support as __LensoNativeSupport;
        let endpoint = ::std::rc::Rc::new($crate::AdminEndpoint::new($provider));
        (
            vec![endpoint.clone() as ::std::rc::Rc<dyn __LensoNativeSupport::NativeRequestEndpoint>],
            vec![],
            vec![],
        )
    }};
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_provide_admin {
    ($provider:expr, $lifecycle:expr, $support:path) => {{
        use $support as __LensoNativeSupport;
        let (request_endpoints, stream_endpoints, event_endpoints) =
            $crate::__lenso_native_endpoints_admin!($provider, $support);
        __LensoNativeSupport::NativePluginInstance::with_all_endpoints(
            request_endpoints,
            stream_endpoints,
            event_endpoints,
            $lifecycle,
        )
    }};
}

#[derive(Debug)]
pub struct AdminClient {
    get_delivery: NativeRequestHandle<AdminGetDelivery>,
    list_deliveries: NativeRequestHandle<AdminListDeliveries>,
    retry_delivery: NativeRequestHandle<AdminRetryDelivery>,
}
impl AdminClient {
    pub fn from_dependencies(dependencies: &PluginDependencies) -> Result<Self, RuntimeFailure> {
        <Self as CapabilityClient>::from_dependencies(dependencies)
    }

    pub async fn get_delivery(&self, request: GetDeliveryRequest) -> Result<GetDeliveryResponse, AdminGetDeliveryInvocationError> {
        self.get_delivery.invoke(GET_DELIVERY_OPERATION, request).await
            .map_err(AdminGetDeliveryInvocationError::Runtime)?
            .map_err(AdminGetDeliveryInvocationError::Domain)
    }

    pub async fn get_delivery_with_context(&self, context: InvocationContext, request: GetDeliveryRequest) -> Result<GetDeliveryResponse, AdminGetDeliveryInvocationError> {
        self.get_delivery.invoke_with_context(GET_DELIVERY_OPERATION, context, request).await
            .map_err(AdminGetDeliveryInvocationError::Runtime)?
            .map_err(AdminGetDeliveryInvocationError::Domain)
    }

    pub async fn list_deliveries(&self, request: ListDeliveriesRequest) -> Result<ListDeliveriesResponse, AdminListDeliveriesInvocationError> {
        self.list_deliveries.invoke(LIST_DELIVERIES_OPERATION, request).await
            .map_err(AdminListDeliveriesInvocationError::Runtime)?
            .map_err(AdminListDeliveriesInvocationError::Domain)
    }

    pub async fn list_deliveries_with_context(&self, context: InvocationContext, request: ListDeliveriesRequest) -> Result<ListDeliveriesResponse, AdminListDeliveriesInvocationError> {
        self.list_deliveries.invoke_with_context(LIST_DELIVERIES_OPERATION, context, request).await
            .map_err(AdminListDeliveriesInvocationError::Runtime)?
            .map_err(AdminListDeliveriesInvocationError::Domain)
    }

    pub async fn retry_delivery(&self, request: RetryDeliveryRequest) -> Result<RetryDeliveryResponse, AdminRetryDeliveryInvocationError> {
        self.retry_delivery.invoke(RETRY_DELIVERY_OPERATION, request).await
            .map_err(AdminRetryDeliveryInvocationError::Runtime)?
            .map_err(AdminRetryDeliveryInvocationError::Domain)
    }

    pub async fn retry_delivery_with_context(&self, context: InvocationContext, request: RetryDeliveryRequest) -> Result<RetryDeliveryResponse, AdminRetryDeliveryInvocationError> {
        self.retry_delivery.invoke_with_context(RETRY_DELIVERY_OPERATION, context, request).await
            .map_err(AdminRetryDeliveryInvocationError::Runtime)?
            .map_err(AdminRetryDeliveryInvocationError::Domain)
    }
}

impl CapabilityClient for AdminClient {
    type Dependencies = PluginDependencies;
    type Error = RuntimeFailure;

    const CAPABILITY_ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn from_dependencies(dependencies: &PluginDependencies) -> Result<Self, RuntimeFailure> {
        Ok(Self {
            get_delivery: dependencies.one::<AdminGetDelivery>()?,
            list_deliveries: dependencies.one::<AdminListDeliveries>()?,
            retry_delivery: dependencies.one::<AdminRetryDelivery>()?,
        })
    }

    fn already_connected() -> RuntimeFailure {
        RuntimeFailure::PluginFailure {
            detail: format!("Capability Port {CAPABILITY_ID} was connected more than once"),
        }
    }
}

impl CapabilityClientMany for AdminClient {
    fn many_from_dependencies(
        dependencies: &PluginDependencies,
    ) -> Result<Vec<BoundCapabilityClient<Self>>, RuntimeFailure> {
        dependencies
            .bindings()
            .iter()
            .filter(|binding| binding.capability_id() == CAPABILITY_ID)
            .map(|binding| {
                Ok(BoundCapabilityClient::new(
                    binding.provider_instance(),
                    Self {
                    get_delivery: binding.handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<AdminGetDelivery>()?,
                    list_deliveries: binding.handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<AdminListDeliveries>()?,
                    retry_delivery: binding.handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<AdminRetryDelivery>()?,
                    },
                ))
            })
            .collect()
    }
}

#[derive(Clone, Debug, PartialEq)]
pub enum AdminGetDeliveryInvocationError {
    Domain(GetDeliveryError),
    Runtime(RuntimeFailure),
}
#[derive(Clone, Debug, PartialEq)]
pub enum AdminListDeliveriesInvocationError {
    Domain(ListDeliveriesError),
    Runtime(RuntimeFailure),
}
#[derive(Clone, Debug, PartialEq)]
pub enum AdminRetryDeliveryInvocationError {
    Domain(RetryDeliveryError),
    Runtime(RuntimeFailure),
}
