// @generated by lenso-contract-codegen; do not edit.
use std::{fmt, rc::Rc};
use futures::future::LocalBoxFuture;
use lenso_kernel::{InvocationContext, NativeRequestEndpoint, NativeRequestFuture, NativeRequestHandle, PluginDependencies, RequestCapability, RuntimeFailure};

use lenso_plugin_authoring::{BoundCapabilityClient, CapabilityClient, CapabilityClientMany};
pub const CAPABILITY_ID: &str = "lenso.email-dispatch@1";
pub const DESCRIPTOR_VERSION: &str = "1.0.0";
pub const PORTABLE: bool = true;
pub const CROSS_LANE_TRANSFER: bool = true;
pub const EMAIL_DISPATCH_CAPABILITY_ID: &str = CAPABILITY_ID;
pub const EMAIL_DISPATCH_DESCRIPTOR_VERSION: &str = DESCRIPTOR_VERSION;

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_provided_email_dispatch { () => { "{\"capability_id\":\"lenso.email-dispatch@1\",\"descriptor_version\":\"1.0.0\",\"operations\":[\"dispatch\"],\"operation_kinds\":{},\"default_admission\":{\"queue_capacity\":0,\"max_concurrency\":1},\"operation_admissions\":{},\"event_admission\":null,\"cross_lane_transfer\":true}" }; }

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_required_email_dispatch_client { () => { "{\"capability_id\":\"lenso.email-dispatch@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"one\"}" }; }

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_required_many_email_dispatch_client { () => { "{\"capability_id\":\"lenso.email-dispatch@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"many\"}" }; }

pub const DISPATCH_OPERATION: &str = "dispatch";

pub use lenso_contract_runtime::{Timestamp, UnknownDomainError};
use lenso_contract_runtime::{decode_portable_json, encode_portable_json};

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct DispatchRequest {
    #[serde(rename = "attempt_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub attempt_id: String,
    #[serde(rename = "correlation_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub correlation_id: String,
    #[serde(rename = "delivery_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub delivery_id: String,
    #[serde(rename = "idempotency_key")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub idempotency_key: String,
    #[serde(rename = "message")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub message: DispatchRequestMessage,
    #[serde(rename = "recipient")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub recipient: DispatchRequestRecipient,
    #[serde(rename = "run_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub run_id: String,
}

#[derive(Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct DispatchRequestMessage {
    #[serde(rename = "content_digest")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub content_digest: String,
    #[serde(rename = "html")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub html: String,
    #[serde(rename = "locale")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub locale: String,
    #[serde(rename = "subject")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub subject: String,
    #[serde(rename = "template_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub template_id: String,
    #[serde(rename = "template_version")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub template_version: String,
    #[serde(rename = "text")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub text: String,
}

impl fmt::Debug for DispatchRequestMessage {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter
            .debug_struct("DispatchRequestMessage")
            .field("content_digest", &self.content_digest)
            .field("html", &"<redacted>")
            .field("locale", &self.locale)
            .field("subject", &"<redacted>")
            .field("template_id", &self.template_id)
            .field("template_version", &self.template_version)
            .field("text", &"<redacted>")
            .finish()
    }
}

#[derive(Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct DispatchRequestRecipient {
    #[serde(rename = "address")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub address: String,
}

impl fmt::Debug for DispatchRequestRecipient {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter
            .debug_struct("DispatchRequestRecipient")
            .field("address", &"<redacted>")
            .finish()
    }
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct DispatchResponse {
    #[serde(rename = "failure")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub failure: Option<DispatchResponseFailure>,
    #[serde(rename = "observed_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub observed_at: Timestamp,
    #[serde(rename = "outcome")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub outcome: DispatchResponseOutcome,
    #[serde(rename = "provider")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub provider: String,
    #[serde(rename = "remote_receipt")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub remote_receipt: Option<DispatchResponseRemoteReceipt>,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct DispatchResponseFailure {
    #[serde(rename = "classification")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub classification: String,
    #[serde(rename = "code")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub code: String,
    #[serde(rename = "retry_after_ms")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub retry_after_ms: Option<i64>,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub enum DispatchResponseOutcome {
    #[serde(rename = "accepted")]
    Accepted,
    #[serde(rename = "temporary_failure")]
    TemporaryFailure,
    #[serde(rename = "permanent_failure")]
    PermanentFailure,
    #[serde(rename = "delivery_unknown")]
    DeliveryUnknown,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct DispatchResponseRemoteReceipt {
    #[serde(rename = "digest")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub digest: String,
    #[serde(rename = "remote_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub remote_id: String,
    #[serde(rename = "source")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub source: String,
}

#[derive(Clone, Debug, PartialEq)]
pub enum DispatchError {
    InvalidDispatch,
    UnsupportedMessage,
    Unknown(UnknownDomainError),
}

#[derive(Debug)]
pub struct EmailDispatch;
impl RequestCapability for EmailDispatch {
    type Request = DispatchRequest;
    type Response = DispatchResponse;
    type DomainError = DispatchError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != DISPATCH_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<EmailDispatchRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).dispatch(context, request)
    }
}

impl serde::Serialize for DispatchError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::InvalidDispatch => serializer.serialize_str("invalid_dispatch"),
            Self::UnsupportedMessage => serializer.serialize_str("unsupported_message"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for DispatchError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "invalid_dispatch" => Ok(Self::InvalidDispatch),
                "unsupported_message" => Ok(Self::UnsupportedMessage),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

pub fn encode_dispatch_request(value: &DispatchRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_dispatch_request(wire: &str) -> Result<DispatchRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_dispatch_response(value: &DispatchResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_dispatch_response(wire: &str) -> Result<DispatchResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_dispatch_error(value: &DispatchError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_dispatch_error(wire: &str) -> Result<DispatchError, serde_json::Error> { decode_portable_json(wire) }

#[doc(hidden)]
pub trait __LensoIntoEmailDispatchDispatchResult {
    fn __lenso_into_result(self) -> Result<Result<DispatchResponse, DispatchError>, RuntimeFailure>;
}
impl __LensoIntoEmailDispatchDispatchResult for Result<DispatchResponse, DispatchError> {
    fn __lenso_into_result(self) -> Result<Result<DispatchResponse, DispatchError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoEmailDispatchDispatchResult for Result<Result<DispatchResponse, DispatchError>, RuntimeFailure> {
    fn __lenso_into_result(self) -> Result<Result<DispatchResponse, DispatchError>, RuntimeFailure> { self }
}
impl __LensoIntoEmailDispatchDispatchResult for Result<DispatchResponse, lenso_plugin_authoring::PluginError<DispatchError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<DispatchResponse, DispatchError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Ok(Err(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoEmailDispatchDispatchResult for Result<DispatchResponse, EmailDispatchInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<DispatchResponse, DispatchError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(EmailDispatchInvocationError::Domain(error)) => Ok(Err(error)),
            Err(EmailDispatchInvocationError::Runtime(error)) => Err(error),
        }
    }
}

pub trait EmailDispatchProvider: fmt::Debug + 'static {
    fn dispatch(&self, context: InvocationContext, request: DispatchRequest) -> NativeRequestFuture<EmailDispatch>;
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_lower_email_dispatch {
    ($plugin:ty, $support:path) => {
        use $support as __LensoNativeSupportEmailDispatch;
        impl $crate::EmailDispatchProvider for $plugin {
        fn dispatch(&self, context: __LensoNativeSupportEmailDispatch::InvocationContext, request: $crate::DispatchRequest) -> __LensoNativeSupportEmailDispatch::NativeRequestFuture<$crate::EmailDispatch> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::dispatch(&plugin, context, request).await;
                $crate::__LensoIntoEmailDispatchDispatchResult::__lenso_into_result(result)
            })
        }
        }
    };
}

#[derive(Debug)]
struct EmailDispatchRequestEndpoint { provider: Rc<dyn EmailDispatchProvider> }

#[derive(Debug)]
pub struct EmailDispatchEndpoint<P: EmailDispatchProvider> { provider: Rc<P>, request_endpoint: EmailDispatchRequestEndpoint }
impl<P: EmailDispatchProvider> EmailDispatchEndpoint<P> {
    pub fn new(provider: P) -> Self {
        let provider = Rc::new(provider);
        let request_provider: Rc<dyn EmailDispatchProvider> = provider.clone();
        Self { provider, request_endpoint: EmailDispatchRequestEndpoint { provider: request_provider } }
    }
}

impl<P: EmailDispatchProvider> NativeRequestEndpoint for EmailDispatchEndpoint<P> {
    fn capability_id(&self) -> &'static str { CAPABILITY_ID }
    fn descriptor_version(&self) -> &'static str { DESCRIPTOR_VERSION }
    fn operations(&self) -> &'static [&'static str] { &[
        DISPATCH_OPERATION,
    ] }
    fn typed_endpoint(&self) -> Option<&dyn std::any::Any> { Some(&self.request_endpoint) }
    fn invoke(&self, operation: &str, request: Box<dyn std::any::Any>, context: InvocationContext) -> LocalBoxFuture<'static, Result<Result<Box<dyn std::any::Any>, Box<dyn std::any::Any>>, RuntimeFailure>> {
        match operation {
            DISPATCH_OPERATION => {
                let Ok(request) = request.downcast::<DispatchRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).dispatch(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            }
            _ => Box::pin(futures::future::ready(Err(RuntimeFailure::UnknownOperation { capability: CAPABILITY_ID, operation: operation.to_owned() }))),
        }
    }
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_endpoints_email_dispatch {
    ($provider:expr, $support:path) => {{
        use $support as __LensoNativeSupport;
        let endpoint = ::std::rc::Rc::new($crate::EmailDispatchEndpoint::new($provider));
        (
            vec![endpoint.clone() as ::std::rc::Rc<dyn __LensoNativeSupport::NativeRequestEndpoint>],
            vec![],
            vec![],
        )
    }};
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_provide_email_dispatch {
    ($provider:expr, $lifecycle:expr, $support:path) => {{
        use $support as __LensoNativeSupport;
        let (request_endpoints, stream_endpoints, event_endpoints) =
            $crate::__lenso_native_endpoints_email_dispatch!($provider, $support);
        __LensoNativeSupport::NativePluginInstance::with_all_endpoints(
            request_endpoints,
            stream_endpoints,
            event_endpoints,
            $lifecycle,
        )
    }};
}

#[derive(Debug)]
pub struct EmailDispatchClient {
    dispatch: NativeRequestHandle<EmailDispatch>,
}
impl EmailDispatchClient {
    pub fn new(handle: NativeRequestHandle<EmailDispatch>) -> Self {
        Self { dispatch: handle }
    }

    pub fn from_dependencies(dependencies: &PluginDependencies) -> Result<Self, RuntimeFailure> {
        <Self as CapabilityClient>::from_dependencies(dependencies)
    }

    pub async fn dispatch(&self, request: DispatchRequest) -> Result<DispatchResponse, EmailDispatchInvocationError> {
        self.dispatch.invoke(DISPATCH_OPERATION, request).await
            .map_err(EmailDispatchInvocationError::Runtime)?
            .map_err(EmailDispatchInvocationError::Domain)
    }

    pub async fn dispatch_with_context(&self, context: InvocationContext, request: DispatchRequest) -> Result<DispatchResponse, EmailDispatchInvocationError> {
        self.dispatch.invoke_with_context(DISPATCH_OPERATION, context, request).await
            .map_err(EmailDispatchInvocationError::Runtime)?
            .map_err(EmailDispatchInvocationError::Domain)
    }
}

impl CapabilityClient for EmailDispatchClient {
    type Dependencies = PluginDependencies;
    type Error = RuntimeFailure;

    const CAPABILITY_ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn from_dependencies(dependencies: &PluginDependencies) -> Result<Self, RuntimeFailure> {
        Ok(Self {
            dispatch: dependencies.one::<EmailDispatch>()?,
        })
    }

    fn already_connected() -> RuntimeFailure {
        RuntimeFailure::PluginFailure {
            detail: format!("Capability Port {CAPABILITY_ID} was connected more than once"),
        }
    }
}

impl CapabilityClientMany for EmailDispatchClient {
    fn many_from_dependencies(
        dependencies: &PluginDependencies,
    ) -> Result<Vec<BoundCapabilityClient<Self>>, RuntimeFailure> {
        dependencies
            .bindings()
            .iter()
            .filter(|binding| binding.capability_id() == CAPABILITY_ID)
            .map(|binding| {
                Ok(BoundCapabilityClient::new(
                    binding.provider_instance(),
                    Self {
                    dispatch: binding.handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<EmailDispatch>()?,
                    },
                ))
            })
            .collect()
    }
}

#[derive(Clone, Debug, PartialEq)]
pub enum EmailDispatchInvocationError {
    Domain(DispatchError),
    Runtime(RuntimeFailure),
}
